### PR TITLE
[ENHANCEMENT] Improve Text Movement

### LINKED ISSUE #35: Bug Report: Improve the text movement on the canvas screen
**Describe the bug**
- currently when we try to move the text, it doesn't feels natural and it doesn't moves with the arrow but a bit ahead.

**To Reproduce**

1. Open the app
2. Create a New Text
3. Try to move the text around
4. See the inconsistency

**Expected behavior**
- Text should move smoothly with the pointer.

**Actual behavior**
- Text has a little faster movement than the pointer.

**Additional details**
- Kindly follow the code pattern, and fix this issue in minimum code changes, try to debug and test yourself, do it by yourself, please don't use AI.

### PR DESCRIPTION
**Pull request by PearlGrell**
## What kind of change does this PR introduce?
This PR enhances the UX of text item movement on the canvas by improving how drag events are captured and updating position state more reliably. It ensures smoother, pixel-accurate movement of draggable text widgets.

## Issue Number:
Fixes #35

### Summary
This PR addresses issues related to inconsistent or jerky text movement when repositioning text items on the canvas. The enhancements include:

- Improved drag responsiveness for _DraggableText widgets.
- Accurate syncing of drag position with CanvasCubit state.
- Correct restoration of position on didUpdateWidget when state changes.

The current setup is functional but can lead to desync between UI and state if the user moves items quickly. This change ensures text position is immediately reflected and persistently stored in the cubit, improving reliability for undo/redo operations.

### CODE REVIEW

File: lib/ui/screens/canvas_screen.dart [hunk 1]
```diff
@@ -115,3 +97,61 @@ class CanvasScreen extends StatelessWidget {
...
+  }
+
+  @override
+  Widget build(BuildContext context) {
+    return Positioned(
+      left: localPosition.dx,
+      top: localPosition.dy,
+      child: GestureDetector(
+        onPanUpdate: (details) {
+          setState(() {
```
Comment (may-tas) [inline lib/ui/screens/canvas_screen.dart:139]: Don't use setState, it slows down things.

Comment (may-tas) [reply lib/ui/screens/canvas_screen.dart:139]: @PearlGrell

Comment (PearlGrell) [reply lib/ui/screens/canvas_screen.dart:139]: @may-tas the problem is if i dont use `setState`, then i will have to update the offset using cubit, but introducing cubit in a fast thing like this, it just introduces a two - three frames delay and it is not so smooth, setState immediately marks it for rebuild, believe me i have tried changes the factor and offsets multiple times, but all with cubit just feel laggy

Comment (may-tas) [reply lib/ui/screens/canvas_screen.dart:139]: Okay, np.

**Comment by may-tas** [comment]
@PearlGrell LGTM, Merging.
